<?php

function slugify($text)
{ 
  // replace non letter or digits by -
  $text = preg_replace('~[^\\pL\d]+~u', '-', $text);

  // trim
  $text = trim($text, '-');

  // transliterate
  $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);

  // lowercase
  $text = strtolower($text);

  // remove unwanted characters
  $text = preg_replace('~[^-\w]+~', '', $text);

  if (empty($text))
  {
      return 'n-a';
  }

  return $text;
}

function ga_api_post($endpoint, $payload) { //Initiate cURL request and send back the result
    $GA_URL = variable_get('geoanalytics_server');
    $GA_USERNAME = variable_get('geoanalytics_user');
    $GA_API_KEY = variable_get('geoanalytics_api_key');
    $GA_LAYERS = variable_get('geoanalytics_layers');
    $GA_DATA = variable_get('geoanalytics_data');
    $GA_STYLES = variable_get('geoanalytics_styles');

    print $GA_URL;
    print $GA_USERNAME;
    print $GA_API_KEY;
    print $GA_LAYERS;
    print $GA_DATA;
    print $GA_STYLES;

    $endpoint .= "?format=json&username=" . $GA_USERNAME . "&api_key=" . $GA_API_KEY;
    error_log(json_encode($payload));

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json','Accept: text/plain'));
    curl_setopt($ch, CURLOPT_URL, $GA_URL . $endpoint);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HEADER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
    curl_setopt($ch, CURLOPT_VERBOSE, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
    curl_setopt($ch, CURLOPT_POST, true); 
    $results = curl_exec($ch);
    if (curl_errno($ch)) {
        print curl_error($ch);
    } else {
        curl_close($ch);
    }
    
    $headers = http_response_headers($results);
    foreach ($headers as $header) {
        $str = ga_http_response_code($header);
        if($str == "500") {
            error_log($results);
        }
        $hdr_arr = http_response_header_lines($header);
        if (isset($hdr_arr['Location'])) {
            return substr($hdr_arr['Location'], strlen($GA_URL));
        }
        else {
            return $GA_URL;
        }
    }
}

function http_response_headers($ret_str)
{
    $hdrs = array();
    $arr = explode("\r\n\r\n", $ret_str);
    foreach ($arr as $each) {
        if (substr($each, 0, 4) == 'HTTP') {
            $hdrs[] = $each;
        }
    }
    return $hdrs;
}

function http_response_header_lines($hdr_str)
{
    $lines = explode("\n", $hdr_str);
    $hdr_arr['status_line'] = trim(array_shift($lines));
    foreach ($lines as $line) {
        list($key, $val) = explode(':', $line, 2);
        $hdr_arr[trim($key)] = trim($val);
    }
    return $hdr_arr;
}

function ga_http_response_code($str)
{
    return substr(trim(strstr($str, ' ')), 0, 3);
}


/**
 * This and _update will cause files that were uploaded into HydroShare to propagate into Geoanalytics
 */
function geoanalytics_node_presave( $node ) {
    $GA_URL = variable_get('geoanalytics_server');
    $GA_USERNAME = variable_get('geoanalytics_user');
    $GA_API_KEY = variable_get('geoanalytics_api_key');
    $GA_LAYERS = variable_get('geoanalytics_layers');
    $GA_DATA = variable_get('geoanalytics_data');
    $GA_STYLES = variable_get('geoanalytics_styles');

    if($node->type == "hydroshare_geoanalytics") {
        // get the file object from the node
        $file = array_shift(field_get_items('node', $node, 'field_file_geoanalytics'));
        $file_path = file_load($file['fid']);
        $web_path = file_create_url($file_path->uri);
        $web_path = $base_url . '/export.php?file=' . $web_path;
        
        //$scheme = file_uri_scheme($file_path->uri);
        //$wrapper = file_stream_wrapper_valid_scheme($scheme);
        //$web_path = $wrapper->getLocalPath($file);
        //$web_path = drupal_realpath($file_path->uri);
        
        $url = parse_url($web_path);
        $path = $url['path'];
        
        // get file metadata
        $title = $node->title;
        $body = $node->body['und'][0]['value'];
        $driver = $node->field_driver['und'][0]['value'];
        $style = $node->field_style['und'][0]['value'];

        // POST a new DataResource record to the geoanalytics API 
        error_log($web_path);
        $ga_dataresource_ref = ga_api_post('/ga_resources/resources/v1/data/', array(
            'resource_url' => $web_path,
            'content' => $body,
            'title' => $title,
            'driver' => $driver,
            'parent' => $GA_DATA 
        ));

        // POST a style record to the geoanalytics API as "default-style"
        $ga_style_ref = ga_api_post('/ga_resources/styles/v1/style/', array(
            'stylesheet' => $style,
            'title' => $title . ' style',
            'content' => $body,
            'parent' => $GA_STYLES
        ));
        $style = slugify($title . ' style');

        // POST a new RenderedLayer record to the geoanalytics API as "wms"
        $ga_renderedlayer_ref = ga_api_post('/ga_resources/layers/v1/rendered_layer/', array(
            'default_style' => $ga_style_ref,
            'styles' => array($ga_style_ref),
            'data_resource' => $ga_dataresource_ref,
            'title' => $title . ' layer',
            'content' => $body,
            'parent' => $GA_LAYERS
        ));
        $layer = slugify($title . ' layer');
        $wms = $GA_URL . '/ga_resources/wms/';

        $node->field_webservice['und'][0]['value'] = $wms;
        $node->field_style_id['und'][0]['value'] = 'styles/' . $style;
        $node->field_layer_id['und'][0]['value'] = 'layers/' . $layer;
    }
}

function geoanalytics_node_update( $node ) {
    if($node->type == "hydroshare_geoanalytics") {
        // PUT a DataResource record to the geoanalytics API
        // PUT a style record to the geoanalytics API
        // PUT a RenderedLayer record to the geoanalytics API
    }
}


/**
 * This will insert the CSS and JS needed to make our Geoanalytics webservice show up as an OpenLayers map
 */
function geoanalytics_preprocess_node( &$variables ) {
    drupal_add_js('http://maps.google.com/maps/api/js?v=3&sensor=false');
    drupal_add_js('http://openlayers.org/dev/OpenLayers.js');
    drupal_add_js('http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js');
    drupal_add_js('/misc/jquery.once.js?v=1.2');
    drupal_add_css('http://openlayers.org/dev/theme/default/style.css');
    drupal_add_css('http://openlayers.org/dev/theme/default/google.css');
    drupal_add_css('http://openlayers.org/dev/examples/style.css');

    drupal_add_js('var geoanalytics_url="' . variable_get('geoanalytics_server') . '";', 'inline');

    drupal_add_js(drupal_get_path('module','geoanalytics').'/singlefile.js', 'file');
}

/**
 * This will actually do all the heavy lifting associated with displaying the map
 */
function geoanalytics_node_view( $node, $view_mode = 'full') {

    // only if in full mode and time_series
    if( $view_mode == "full" && $node->type == "hydroshare_geoanalytics" ) {

        // get the WMS service address from the node
        $wms   = $node->field_webservice['und'][0]['value'];
        $wfs   = preg_replace('wms',  'wfs', $wms);
        $style = $node->field_style_id['und'][0]['value'];
        $layer = $node->field_layer_id['und'][0]['value'];
        $features = preg_replace('-layer','',$layer);
 
        // inject target div
        $node->content['render_target'] = array(
            '#markup' => '<div id="hydroshare_vizualization" style="height:340px;"></div>' . 
                         '<ul id="hydroshare_services">' .
                         '  <lh>Web services. Right click to copy link address.</lh>' .
                         "  <li><a href='$wms&service=WMS&request=GetMap&layers=$layer&style=$style'>Web Map Service (WMS).</li>" . 
                         "  <li><a href='$wfs&service=WFS&request=GetFeatures&layers=$layer&format=GeoJSON&count=0'>Web Feature Service (WFS) as GeoJSON.</li>" .
                         "  <li><a href='$wfs&service=WFS&request=GetFeatures&layers=$layer&format=Shapefile&count=0'>Web Feature Service (WFS) as Shapefile.</li>" .
                         "  <li><a href='$wfs&service=WFS&request=GetFeatures&layers=$layer&format=SQLite&count=0'>Web Feature Service (WFS) as SQLite.</li>" .
                         '</ul>',
            '#weight' => 0,
        );

        // call render
        $node->content['render_single'] = array(
            '#markup' => "<script>hydroshare_viz_script_makemap('$wms', '$layer', '$style');</script>",
            '#weight' => 50,
        );

    }

    return $node;

} // geoanalytics_node_view

function geoanalytics_admin() {
    $form = array();

    $form['geoanalytics_server'] = array(
        '#type' => 'textfield',
        '#title' => t('Geoanalytics server url'),
        '#default_value' => variable_get('geoanalytics_server', 'http://ga.renci.org'),
        '#size' => 24,
        '#maxlength' => 1024,
        '#description' => t("The base url of the Geoanalytics web server to store GIS data in."),
        '#required' => TRUE,
    );
    $form['geoanalytics_user'] = array(
        '#type' => 'textfield',
        '#title' => t('Geoanalytics username'),
        '#default_value' => variable_get('geoanalytics_user', 'hydroadmin'),
        '#size' => 24,
        '#maxlength' => 1024,
        '#description' => t("The username for the geoanalytics user"),
        '#required' => TRUE,
    );
    $form['geoanalytics_api_key'] = array(
        '#type' => 'textfield',
        '#title' => t('Geoanalytics api key'),
        '#default_value' => variable_get('geoanalytics_api_key', ''),
        '#size' => 24,
        '#maxlength' => 1024,
        '#description' => t("The automatically generated API key for the geoanalytics user"),
        '#required' => TRUE,
    );
    $form['geoanalytics_layers'] = array(
        '#type' => 'textfield',
        '#title' => t('Layer page URI'),
        '#default_value' => variable_get('geoanalytics_layers', '/ga_resources/resources/v1/catalog/layers/'),
        '#size' => 24,
        '#maxlength' => 1024,
        '#description' => t("The URI of the catalog page that will contain layers"),
        '#required' => TRUE,
    );
    $form['geoanalytics_data'] = array(
        '#type' => 'textfield',
        '#title' => t('Data page URI'),
        '#default_value' => variable_get('geoanalytics_data', '/ga_resources/resources/v1/catalog/data/'),
        '#size' => 24,
        '#maxlength' => 1024,
        '#description' => t("The URI of the catalog page that will contain data"),
        '#required' => TRUE,
    );
    $form['geoanalytics_styles'] = array(
        '#type' => 'textfield',
        '#title' => t('Styles page URI'),
        '#default_value' => variable_get('geoanalytics_styles', '/ga_resources/resources/v1/catalog/styles/'),
        '#size' => 24,
        '#maxlength' => 1024,
        '#description' => t("The URI of the catalog page that will contain styles"),
        '#required' => TRUE,
    );

    return system_settings_form($form);
}
function geoanalytics_menu() {

      $items = array();

      $items['admin/settings/geoanalytics'] = array(
            'title' => 'On this date module settings',
            'description' => 'Description of your On this date settings page',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('geoanalytics_admin'),
            'access arguments' => array('administer geoanalytics settings'),
            'type' => MENU_NORMAL_ITEM,
     );

     return $items;
}
?>
