<?php

// Hook where we will add the custom submit handler for each form id
function renci_custom_form_alter(&$form, &$form_state, $form_id){
  // Add custom form ids here
  if ($form_id == 'user_login' || $form_id == 'user_login_block') { 
		$form['actions']['submit']['#value'] = t("SIGN IN");
  }
  if ($form_id == 'user_register_form') { 
    drupal_set_title(t('Create new account')); 
  } 
  if ($form_id == 'user_pass') { 
    drupal_set_title(t('Request new password')); 
  }

  
}

/**
 * Implementation of expand_password_confirm.
 */
function renci_custom_form_password_confirm($element) {
  $element['pass1']['#title'] = t("New Password");
  $element['pass2']['#title'] = t("Confirm New Password");
  return $element;
}

?>