<?php

/**
 * @file
 * Module file for services_basic_auth module.
 */

/**
 * Implements hook_services_authentication().
 */
function services_basic_auth_services_authentication_info() {
  return array(
    'file'             => 'services_basic_auth.inc',
    'title'            => t('HTTP basic authentication'),
    'description'      => t('Username and password are sent in each request'),
    'authenticate_call' => '_services_basic_auth_authenticate_call',
  );
}

/**
 * Implements hook_rest_server_execute_errors_alter().
 *
 * HTTP Basic Authentication must add a "WWW-Authenticate" header on
 * unauthorized requests. Some clients (i.e. lynx) will not work properly
 * without this.
 *
 * This hook was introduced in the services module version 3.3 and will have no
 * effect on versions prior to this.
 */
function services_basic_auth_rest_server_execute_errors_alter(&$error, $controller, $arguments) {
  if ($error['code'] == 401) {
    drupal_add_http_header('WWW-Authenticate', 'Basic realm="' . check_plain(variable_get('site_name'), 'Drupal') . '"');
  }
}
