<?php


function hydrology_model_visualization_preprocess_node( &$variables ) {
    drupal_add_js('http://d3js.org/d3.v3.js', 'external');
    drupal_add_css(drupal_get_path('module','hydrology_model_visualization').'/hydrology_model_visualization.css', 'file');
    drupal_add_js(drupal_get_path('module','hydrology_model_visualization').'/hydrology_model_visualization.js', 'file');
}

function hydrology_model_visualization_node_view( $node, $view_mode = 'full') {

    // only if in full mode and time_series
    if( $view_mode == "full" && $node->type == "hydroshare_hydrology_model" ) {

        // inject target div
        $node->content['render_target'] = array(
            '#markup' => '<div id="hydroshare_vizualization"></div>',
            '#weight' => 0,
        );

        // get the file object from the node
        $file      = NULL;
        $real_path = NULL;
        if( true == data_model_get_file_from_node( $node, $file ) ) {
            $web_path = file_create_url( $file->uri );
            move_model($file);
        } else {
            error_log( "time_series_visualization_node_view :: failed to get file for node" );
            return NULL;
        }

        // get file metadata
        $source = NULL;
        data_model_get_node_metadata_field_value( $node, "source", $source );

        
        // get plot data from parser (using model name)
        $parser_class = $node->field_model_name['und'][0]['value']; 
        $parser = new $parser_class;
        if(method_exists($parser,'get_single_output')){
          
        // get model directory
        $wrapper = file_stream_wrapper_get_instance_by_uri($file->uri);
        $path = $wrapper->realpath();
        $model_path = dirname($path).'/model';

        // get single output data series from parser
        $data = $parser->get_single_output($node, $model_path);   
                   
        // encode plot data into json
        $json = json_encode($data);

        // add plot function call to content
        $node->content['render_single'] = array(
          '#markup' => "<script>hydrology_model_plot_single(".$json.")</script>",
          '#weight' => 50,
          );
        }        
    }
    return $node;
}

function move_model($zip_file){
      
  //-- Move the model into 'files' folder

      $wrapper = file_stream_wrapper_get_instance_by_uri($zip_file->uri);
      $path = $wrapper->realpath();
      $model_path = dirname($path); //.'/model';
    
    // unzip the model if the model dir doesnt exist
    if(!file_exists(dirname($path).'/model')){

        $zip = new ZipArchive;
        $res = $zip->open($path);
        if ($res == TRUE){

          // get the model folder name by peeking into zip
          $z = zip_open($path);
          $zip_entry = zip_read($z);
          $model_folder = zip_entry_name($zip_entry);
          $model_folder = array_slice(explode('/',$model_folder),0,1);

          // extract the model contents
          $zip->extractTo($model_path);
          $zip->close();

          // rename the model folder to something more standardized
          rename($model_path.'/'.$model_folder[0], $model_path.'/model');

        }
    }
  
}