<?php

// Hook where we will add the custom submit handler for each form id
function renci_custom_form_alter(&$form, &$form_state, $form_id){
  // Add custom form ids here
  if ($form_id == 'user_login' || $form_id == 'user_login_block') { 
		$form['actions']['submit']['#value'] = t("SIGN IN");
	  
		$form['actions']['recover_pwd_btn'] = array(
		    '#type' => 'button',
		    '#submit' => array('renci_custom_user_login_recover_pwd_submit'),
		    '#limit_validation_errors' => array(),		
		    '#attributes' =>  array('style' => array('width:300px'), 'onclick' => array('window.location=\'/?q=user/password\';return false;')),
		    '#value' => t('RECOVER LOST PASSWORD'),
  			);
  }
  if ($form_id == 'user_register_form') {
  	    $form['account']['name']['#title'] = t("Requested Username ");
		$form['account']['mail']['#title'] = t("Requested E-mail address ");	  
 		$form['actions']['submit']['#value'] = t("Request New Account");
  } 
  if ($form_id == 'user_pass') { 
    $form['actions']['submit']['#attributes'] = array('style' => array('width:300px'));
  }
  if ($form_id ==  'user_profile_form') {
	  $form['account']['pass']['#process'] = array(
		    'form_process_password_confirm',
		    'renci_custom_form_process_password_confirm'
	  		);
  	
  }
  
}

/**
 * Implementation of expand_password_confirm.
 */
function renci_custom_form_process_password_confirm($element) {
  $element['pass1']['#title'] = t("New Password");
  $element['pass2']['#title'] = t("Confirm New Password");
  return $element;
}

/**
 * Implementation of expand_password_confirm.
 */
function renci_custom_user_login_recover_pwd_submit($form, &$form_state) {
  drupal_goto('/?q=user/password', array('external' => TRUE));
}

?>